### PR TITLE
Make memory usage reading support EKS

### LINKED ISSUE #20: None of the methods for collecting memory limit and usage work in EKS
Using the 0.3.3 version of the library, the following two methods for figuring out memory limit and usage from the OS seems to fail to return any values in my EKS cluster:

1. `lc_lib:do_get_cgroup_memory_usage/0` parses the cgroup memory path correctly (https://github.com/emqx/lc/issues/17 works!) and constructs the filename correctly, but the resulted file (`/sys/fs/cgroup/memory/kubepods.slice/kubepods-pod30d0fb1f_937d_45c1_b986_fd363a73f1ea.slice/cri-containerd-3bf62db008468812fcafe483b22a094339421d780dccee198a27d105e828c2f4.scope/memory.usage_in_bytes`) does not exist
2. `lc_lib:get_cgroup2_memory_usage/0` also fails because `/sys/fs/cgroup/memory.current` does not exist either

I would suggest to include a 3rd method that I found working:
```
do_get_cgroup3_memory_usage() ->
    try
        CgroupUsed = read_int_fs(filename:join(["/sys/fs/cgroup/memory",
            "memory.usage_in_bytes"])
        ),
        CgroupTotal = read_int_fs(filename:join(["/sys/fs/cgroup/memory",
            "memory.limit_in_bytes"])),
        {CgroupUsed/CgroupTotal, CgroupTotal}
    catch error:_ ->
        {0, 0}
    end.
```
The above method parse these values:
```
$ cat /sys/fs/cgroup/memory/memory.usage_in_bytes
761204736
$ cat /sys/fs/cgroup/memory/memory.limit_in_bytes 
3145728000
```
```
> lc_lib:get_cgroup_memory_usage(). 
0
> lc_lib:get_cgroup2_memory_usage().
0
> lc_lib:get_cgroup3_memory_usage().
0.24186197916666666
```

### PR DESCRIPTION
**Pull request by egertak**
fix: #20 
Using the 0.3.3 version of the library, the following two methods for figuring out memory limit and usage from the OS seems to fail to return any values in my EKS cluster:

1. `lc_lib:do_get_cgroup_memory_usage/0` parses the cgroup memory path correctly (https://github.com/emqx/lc/issues/17 works!) and constructs the filename correctly, but the resulted file (`/sys/fs/cgroup/memory/kubepods.slice/kubepods-pod30d0fb1f_937d_45c1_b986_fd363a73f1ea.slice/cri-containerd-3bf62db008468812fcafe483b22a094339421d780dccee198a27d105e828c2f4.scope/memory.usage_in_bytes`) does not exist
2. `lc_lib:get_cgroup2_memory_usage/0` also fails because `/sys/fs/cgroup/memory.current` does not exist either

I would suggest to include a 3rd method that I found working:
```
do_get_cgroup3_memory_usage() ->
    try
        CgroupUsed = read_int_fs(filename:join(["/sys/fs/cgroup/memory",
            "memory.usage_in_bytes"])
        ),
        CgroupTotal = read_int_fs(filename:join(["/sys/fs/cgroup/memory",
            "memory.limit_in_bytes"])),
        {CgroupUsed/CgroupTotal, CgroupTotal}
    catch error:_ ->
        {0, 0}
    end.
```
The above method parse these values:
```
$ cat /sys/fs/cgroup/memory/memory.usage_in_bytes
761204736
$ cat /sys/fs/cgroup/memory/memory.limit_in_bytes 
3145728000
```
```
> lc_lib:get_cgroup_memory_usage(). 
0
> lc_lib:get_cgroup2_memory_usage().
0
> lc_lib:get_cgroup3_memory_usage().
0.24186197916666666
```

### CODE REVIEW

**Review by qzhuyan — APPROVED** [review]

File: src/lc_lib.erl [hunk 1]
```diff
@@ -131,6 +133,23 @@ do_get_cgroup2_memory_usage() ->
...
+get_cgroup3_memory_usage() ->
+  {Ratio, _Total} = do_get_cgroup3_memory_usage(),
+  Ratio.
+
+do_get_cgroup3_memory_usage() ->
+  try
+    CgroupUsed = read_int_fs(filename:join(["/sys/fs/cgroup/memory",
+      "memory.usage_in_bytes"])
+    ),
+    CgroupTotal = read_int_fs(filename:join(["/sys/fs/cgroup/memory",
```
Comment (qzhuyan) [inline src/lc_lib.erl:146]: I found that without the exact slice path, the value you get is not exact value k8s set for the pod, it could be a system wide limit. 

```
ubuntu@amiable-capelin:~$ cat /sys/fs/cgroup/memory/user.slice/user-1000.slice/session-3.scope/memory.usage_in_bytes
4055040
ubuntu@amiable-capelin:~$ cat /sys/fs/cgroup/memory/memory.usage_in_bytes
560300032

```

Comment (egertak) [reply src/lc_lib.erl:146]: Good finding! I'll check if the slice path works in the EKS environment. If it does, I'll update the PR accordingly.

File: src/lc_lib.erl [hunk 2]
```diff
@@ -131,6 +133,23 @@ do_get_cgroup2_memory_usage() ->
     {0, 0}
   end.
 
+-spec get_cgroup3_memory_usage() -> number().
+get_cgroup3_memory_usage() ->
```
[the remark this answers is not in the document]
Comment (egertak) [reply src/lc_lib.erl:137]: Oh, right! Got it!

File: src/lc_lib.erl (hunk 1 above)
Comment (qzhuyan) [reply src/lc_lib.erl:146]: just to clarify,  the slice path is read from `/proc/self/cgroup` in the pod.

will be interesting to see what is in the `/proc/self/cgroup` because the original `get_cgroup_memory_usage` relies on that.

**Comment by egertak** [comment]
@qzhuyan I've revised the solution. Please check! I've removed the 3rd function to avoid confusion. It now works with all my cases, including EKS and native Ubuntu. For the later I had to add slice /proc/self/cgroup based discovery to cgroups version 2 as well, similar to how it is done in version 1.

File: src/lc_lib.erl (hunk 1 above)
Comment (qzhuyan) [reply src/lc_lib.erl]: thanks for the insight!

**Comment by qzhuyan** [comment]
LGTM

**Review by qzhuyan — APPROVED** [review]

**Comment by qzhuyan** [comment]
@egertak appreciate for the PR, merged!
